-- ======================================================================
-- RETURNS THE DAY OF THE WEEK A TIMESTAMP BELONGS TO, HAS THE SAME BEHAVIOR AS THE TD_DAY_OF WEEK FUNCTION FROM TERADATA
-- PARAMETERS:
--      INPUT: TIMESTAMP_TZ. DATE TO GET THE DAY OF WEEK FROM
-- RETURNS:
--      AN INTEGER BETWEEN 1 AND 7 WHERE 1 = SUNDAY, 2 = MONDAY, ..., 7 = SATURDAY
-- ======================================================================
CREATE OR REPLACE FUNCTION PUBLIC.TD_DAY_OF_WEEK_UDF(INPUT TIMESTAMP_TZ)
RETURNS INT
LANGUAGE SQL
IMMUTABLE
AS
$$
    IFF(DAYOFWEEKISO(INPUT) = 7, 1, DAYOFWEEKISO(INPUT) + 1)
$$;